/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { UIContext } from "../../src/App"
import { useHueMat } from './hueMaterial'


const Eyes2Model = forwardRef( (props, ref) => {
  const { currentShape, modelColor } = useContext(UIContext);
  const { nodes, materials } = useGLTF('../geometry/site/eyes2.gltf');
  const tmap = useTexture('../images/lightbakes/eyes2.png');
  const matColor = new THREE.Color(modelColor.find(d => d.name == "eyes").color);
  let visibility = currentShape.eyes.models[currentShape.eyes.curr] == "eyes2";
  const mat = useHueMat(matColor, tmap, false);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        material={mat}
        visible={visibility}
        castShadow
        receiveShadow
        geometry={nodes.eyes1.geometry}
        // material={nodes.head.material}
        userData={{modelType: "eyes2"}}
      >
      </mesh>
    </group>
  )
})

useGLTF.preload('../geometry/site/eyes2.gltf')

export default Eyes2Model;