/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { UIContext } from "../../src/App"
import { useHueMat } from "./hueMaterial";


const Eyes4Model = forwardRef( (props, ref) => {
  const { currentShape, modelColor, currentCount } = useContext(UIContext);
  const { nodes, materials } = useGLTF('../geometry/site/eyes4.gltf');
  const tmap = useTexture('../images/lightbakes/eyes4.png');
  const matColor = new THREE.Color(modelColor.find(d => d.name == "eyes").color);
  let visibility = currentShape.eyes.models[currentShape.eyes.curr] == "eyes4";
  let active = visibility && modelColor[currentCount].name == "eyes";
  const mat = useHueMat(matColor, tmap, active);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        material={mat}
        visible={visibility}
        castShadow
        receiveShadow
        geometry={nodes.eyes4.geometry}
        // material={nodes.head.material}
        userData={{modelType: "eyes4"}}
      >
      </mesh>
    </group>
  )
})

useGLTF.preload('../geometry/site/eyes4.gltf')

export default Eyes4Model;