/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { extend } from "@react-three/fiber"
import { useGLTF, useTexture } from '@react-three/drei'
import { UIContext } from "../../src/App"
import HueMaterial from "./hueMaterial"

extend({ HueMaterial })

const Eyes4Model = forwardRef( (props, ref) => {
  const { currentShape, modelColor } = useContext(UIContext);
  const { nodes, materials } = useGLTF('../geometry/site/eyes4.gltf');
  const tmap = useTexture('../images/lightbakes/eyes4.png');
  const matColor = new THREE.Color(modelColor.find(d => d.name == "eyes").color);
  let visibility = currentShape.eyes.models[currentShape.eyes.curr] == "eyes4";

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        visible={visibility}
        castShadow
        receiveShadow
        geometry={nodes.eyes4.geometry}
        // material={nodes.head.material}
        userData={{modelType: "eyes4"}}
      >
        <hueMaterial 
          tMap={ tmap }
          uColor={ new THREE.Color("white") } 
          uColor2={ matColor }
          uColor3={ new THREE.Color("red") }
          uBrightess={ 0.1 }
          attach="material" />
      </mesh>
    </group>
  )
})

useGLTF.preload('../geometry/site/eyes4.gltf')

export default Eyes4Model;