/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { extend } from "@react-three/fiber"
import { useGLTF, useTexture } from '@react-three/drei'
import { UIContext } from "../../src/App"
import HueMaterial from "./hueMaterial"

extend({ HueMaterial })

const EyesModel = forwardRef( (props, ref) => {
  const { modelColor } = useContext(UIContext);
  const { nodes, materials } = useGLTF('./geometry/site/eyes.gltf');
  const tmap = useTexture('./images/lightbakes/eyes.png');
  const matColor = new THREE.Color(modelColor.find(d => d.name == "eyes").color);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.eyes.geometry}
        // material={nodes.head.material}
        userData={{modelType: "eyes"}}
      >
        <hueMaterial 
          tMap={ tmap }
          uColor={ new THREE.Color("white") } 
          uColor2={ new THREE.Color("grey") }
          uColor3={ new THREE.Color("red") }
          uBrightess={ 0.1 }
          attach="material" />
      </mesh>
    </group>
  )
})

useGLTF.preload('./geometry/site/eyes.gltf')

export default EyesModel;