/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function HeadModel(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./geometry/site/head.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.head.geometry}
        material={nodes.head.material}
      />
    </group>
  )
}

useGLTF.preload('./geometry/site/head.gltf')
