/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { extend } from "@react-three/fiber"
import { useGLTF, useTexture } from '@react-three/drei'
import { UIContext } from "../../src/App"
import HueMaterial from "./hueMaterial"

extend({ HueMaterial })

const HeartglassesModel = forwardRef( (props, ref) => {
  const { currentShape, modelColor } = useContext(UIContext);
  const { nodes, materials } = useGLTF('../geometry/site/heartglasses.gltf');
  const tmap = useTexture('../images/lightbakes/heartglasses.png');
  const matColor = new THREE.Color(modelColor.find(d => d.name == "glasses").color);
  let visibility = currentShape.glasses.models[currentShape.glasses.curr] == "heartglasses";

  return (
    <group {...props} dispose={null}>
      <mesh
        position={[0,.1,0]}
        ref={ref}
        visible={visibility}
        castShadow
        receiveShadow
        geometry={nodes.heartglasses1.geometry}
        // material={nodes.head.material}
        userData={{modelType: "chest"}}
      >
        <hueMaterial 
          tMap={ tmap }
          uColor={ matColor } 
          uColor2={ matColor }
          uColor3={ matColor }
          uBrightess={ 0.1 }
          attach="material" />
      </mesh>
    </group>
  )
})

useGLTF.preload('../geometry/site/heartglasses.gltf')

export default HeartglassesModel;