/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { UIContext } from "../../src/App"
import { useHueMat } from './hueMaterial'


const HeartglassesModel = forwardRef( (props, ref) => {
  const { currentShape, modelColor, currentCount } = useContext(UIContext);
  const { nodes, materials } = useGLTF('../geometry/site/heartglasses.gltf');
  const tmap = useTexture('../images/lightbakes/heartglasses.png');
  const matColor = new THREE.Color(modelColor.find(d => d.name == "glasses").color);
  let visibility = currentShape.glasses.models[currentShape.glasses.curr] == "heartglasses";
  let active = visibility && modelColor[currentCount].name == "glasses";
  const mat = useHueMat(matColor, tmap, active);

  return (
    <group {...props} dispose={null}>
      <mesh
        position={[0,.1,0]}
        ref={ref}
        material={mat}
        visible={visibility}
        castShadow
        receiveShadow
        geometry={nodes.heartglasses1.geometry}
        // material={nodes.head.material}
        userData={{modelType: "chest"}}
      >
      </mesh>
    </group>
  )
})

useGLTF.preload('../geometry/site/heartglasses.gltf')

export default HeartglassesModel;