/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { extend } from "@react-three/fiber"
import { useGLTF, useTexture } from '@react-three/drei'
import { UIContext } from "../../src/App"
import HueMaterial from "./hueMaterial"

extend({ HueMaterial })

const MouthModel = forwardRef( (props, ref) => {
  const { modelColor } = useContext(UIContext);
  const { nodes, materials } = useGLTF('./geometry/site/mouth.gltf');
  const tmap = useTexture('./images/lightbakes/mouth.png');
  const matColor = new THREE.Color(modelColor.mouth);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.mouth.geometry}
        // material={nodes.head.material}
        userData={{modelType: "mouth"}}
      >
        <hueMaterial 
          tMap={ tmap }
          uColor={ matColor } 
          uColor2={ matColor }
          uColor3={ matColor }
          uBrightess={ 0.1 }
          attach="material" />
      </mesh>
    </group>
  )
})

useGLTF.preload('./geometry/site/mouth.gltf')

export default MouthModel;