/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { UIContext } from "../App"
import { useHueMat } from './hueMaterial'


const HeadModel = forwardRef( (props, ref) => {
  const { modelColor, currentCount } = useContext(UIContext);
  const { nodes, materials } = useGLTF('/geometry/site/head.gltf')
  const tmap = useTexture('/images/lightbakes/head.png');
  const matColor = new THREE.Color(modelColor.find(d => d.name == "skin").color);
  let active = modelColor[currentCount].name == "skin";
  const mat = useHueMat(matColor, tmap, active);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        material={mat}
        castShadow
        receiveShadow
        geometry={nodes.head.geometry}
        // material={nodes.head.material}
        userData={{modelType: "head"}}
      >
      </mesh>
    </group>
  )
})

useGLTF.preload('/geometry/site/head.gltf')

export default HeadModel;