/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { UIContext } from "../App"
import { useHueMat } from "./hueMaterial";


const ParkaModel = forwardRef( (props, ref) => {
  const { currentShape, modelColor, currentCount } = useContext(UIContext);
  const { nodes, materials } = useGLTF('/geometry/site/parka.gltf');
  const tmap = useTexture('../images/lightbakes/parka.png');
  const matColor = new THREE.Color(modelColor.find(d => d.name == "chest").color);
  let visibility = currentShape.chest.models[currentShape.chest.curr] == "parka";
  let active = visibility && modelColor[currentCount].name == "chest";
  const mat = useHueMat(matColor, tmap, active);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        material={mat}
        visible={visibility}
        castShadow
        receiveShadow
        geometry={nodes.parka.geometry}
        // material={nodes.head.material}
        userData={{modelType: "chest"}}
      >
      </mesh>
    </group>
  )
})

useGLTF.preload('/geometry/site/parka.gltf')

export default ParkaModel;