/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useRef, useContext } from 'react'
import { extend } from "@react-three/fiber"
import { useGLTF, useTexture } from '@react-three/drei'
import BackMaterial from "../backMaterial"

extend({ BackMaterial })

const BackplaneModel = forwardRef( (props, ref) => {
  const { nodes, materials } = useGLTF('../geometry/site/home/backplane.gltf');

  return (
    <group {...props} dispose={null}>
      <mesh
        position={ [0,0,3] }
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        // material={nodes.head.material}
        userData={{modelType: "backplane"}}
      >
        <backMaterial 
          uColor={ new THREE.Color("#1e1e1e") } 
          uColor2={ new THREE.Color("green") }
          uColor3={ new THREE.Color("red") }
          uColorBackground={ new THREE.Color("#8b42f9") }
          uBackground={ 1.0 }
          uBrightnss={ 0.1 }
          attach="material" />
      </mesh>
    </group>
  )
})

useGLTF.preload('../geometry/site/home/backplane.gltf')

export default BackplaneModel;